### ISSUE TITLE
Awesome implementation!

### ISSUE THREAD

**Issue by zenoware** [alveflo/tsmediator#1]
So I love this approach and want to use it but forcing typings is a bit weird.  Why not use @types?  And is there a work around for this?

**Comment by alveflo** [comment]
thanks, glad to hear that you like the approach :) fyi though this implementation was more of a sunday afternoon project kinda thing, so as you mentioned there probably are some design flaws

anyway, about the typings - I'm not sure if I understand exactly what you mean, could you please elaborate? because I'm not sure if you mean the actual types or the `Type: string` that needs to be declared in each handler. if you refer to the latter, I agree that it kinda sucks so if you have any idea of how to make it better please enlight me haha

**Comment by zenoware** [comment]
What I mean is that instead of using typings in your package, just include @types/chai, etc in dev-dependencies.  I created a fork for it and a PR.  Basically, typings in deprecated so needs to be removed.  It was causing an issue with the post-installation steps.

**Comment by alveflo** [comment]
oh yeah I realized that when I saw your pr. however the build fails, so I figured I will look into it tonight. thanks for your contribution!

**Comment by alveflo** [comment]
fixed in #4
